### PR TITLE
Update Zero founders addresses

### PR DESCRIPTION
**Pull request by Gumbees**
Updated to add ZERO's treasury  model starting at block 410000.

### CODE REVIEW

**Comment by egyptianbman** [comment]
From Discord:

Testnet:
```
"t2BEnZwurNtPyhyWdZ82zTdS93rKyoUpgMJ",
          "t2AwNRubry4rQrEvHwAdpYve4Gz5cSmjGXA",
          "t2FM2EZqQZANA18rbhBGLWbxKcpGk9soAvS",
          "t2TBZfnXRCmFPc3nSrQcNtnR6AGWNzF9hzz",
          "t2QMyS1C3jXJ5hcR7zJTPSbWFvMWQEyjVTE",
          "t2SxA3E34aZJDDxnUxC2gZXBVrXWuoH5v7W",
          "t2FhR8STLvuKTUPgM586T1LMUG4JAHV2XSt",
          "t2NScRwr3FHPN8fNSgMKn8ngZG2kgfC8JNt",
          "t2LYZj3LiCDaCGUXQNXH1ZFPmHiC46wB9se",
          "t28azskSALVTtgbW63CqDwzXgtWQ56GVVXa"

Last foundersreward will be at block 29999, halvinginterval is 3000
```

Mainnet:
```
"t3hmg6WApjqVFw9oPWTDy4JLEqXcUWthg5v", 
          "t3hrh5M7eaGA5zXCitPXz2pbe146GkVPWHs",
          "t3aWmHqBGS7watoKQLa7uykeTaYHoYqM361",
          "t3hsi89hPsZzmnbs3pny6cfAxMxV5TJLErj", 
          "t3TdGxPVUdMXd6qDrDCEuJETLadZ9Ki3s9r",
          "t3cb5ZjKmbGbqDaYk97Auam9kXXikGQBmyY",
          "t3V1YovGUPW9WSBoAHS48FDdUfUTo6LDpZR",
          "t3KB9n28MVg31oo856t1tQGfJuYq8usTvSi", 
          "t3dqSV4YGj5V3WjQhqFGrKTMUf9Tgc6xnJM",
          "t3aJkYT1i6tyytq8J6khPaDNtgZsBSXgfBf", 

Last foundersreward will be at block 7999999, halving interval is 800000
```

**Comment by Gumbees** [comment]
@egyptianbman I'll update this. So they're getting founders rewards too then?

Edit: Okay I get it now. Not going to use treasury model here. Just going to add option blockHeightStartFoundersReward.

**Comment by Gumbees** [comment]
@egyptianbman ready for review again. I'll add and test out the startFoundersRewardBlockHeight in another branch.

**Comment by egyptianbman** [comment]
It looks good to me but we should wait until we can test it against testnet in about 48 hours.

**Review by egyptianbman — APPROVED** [review]
Thanks!

**Pull request merged**
