### PR TITLE
Use official ZenCash explorer

### PR DESCRIPTION
**Pull request by tarrenj**
Use official ZenCash explorers

Fixes https://github.com/z-nomp/z-nomp/issues/20

### CODE REVIEW

**Comment by egyptianbman** [comment]
Thanks, @tarrenj! I apologize, can you change the target for this commit to the master branch? Sorry -- I merged the other PR before I noticed this PR is based on it.

**Review by Gumbees — DISMISSED** [review]
@tarrenj Can you change the target to the new master branch? This branch was already merged into master before your changes. Thanks!

**Comment by tarrenj** [comment]
@nettts Target changed.  If you guys don't want to use the official explorer you don't have to.  I just thought it might be a good idea.  Please don't consider this an official request from ZenCash if you'd rather use the zen-solutions one.

**Comment by Gumbees** [comment]
@tarrenj can you make sure your fork is in sync with master one last time? I'll approve and merge today if you can do this for me. Thanks.

**Comment by tarrenj** [comment]
Done.

**Comment by Gumbees** [comment]
@tarrenj

I visited your branch in your fork and it still states it is 12 commits behind master.

```This branch is 4 commits ahead, 12 commits behind z-nomp:master.```

**Comment by tarrenj** [comment]
Whoops! You're right, I'll close this PR, refork, make the change and submit a new PR now. That way the commit tree is less messy.

**Pull request closed without merging**
