### PR TITLE
add unix domain socket support for redis

### PR DESCRIPTION
**Pull request by mkrufky**
Set `config.redis.socket` to your redis socket (`/var/run/redis/redis.sock`) to enable UNIX domain sockets.

Otherwise, set `config.redis.host` & `config.redis.port` for standard tcp connections.

standard connection:
```json
    "redis": {
        "host": "127.0.0.1",
        "port": 6379,
        "password": ""
    },
```

unix domain socket connection:
```json
    "redis": {
        "socket": "/var/run/redis/redis.sock",
        "password": ""
    },
```

### CODE REVIEW

**Comment by LOUD-Mining** [comment]
Applied to LOUD Mining all is good...  No adverse effects...

**Comment by greerso** [comment]
I just tried this on [Beard Pool](https://beardpool.rocks).  Here is the before and after:

Before.
```
1|zelpool  | 2019-07-07 17:48:12 [Pool]    [zelcash] (Thread 2) Share processing setup with redis (127.0.0.1:6379)  
1|zelpool  | 2019-07-07 17:40:30 [Payments]    [zelcash] Finished interval - time spent: 30ms total, 15ms redis, 10ms daemon RPC
```

After.
```
2019-07-07 18:02:38 [Pool]    [zelcash] (Thread 2) Share processing setup with redis (/run/redis/redis-server.sock)  
2019-07-07 18:04:08 [Payments]    [zelcash] Finished interval - time spent: 26ms total, 8ms redis, 3ms daemon RPC
```

Much faster redis

**Comment by wattpool** [comment]
This patch is applied on the VerusCoin pool at [verus.wattpool.net](https://verus.wattpool.net) - also seeing about 8-12 ms time savings when using unix domain sockets instead of host:port

**Comment by wattpool** [comment]
This patch is applied on the VerusCoin pool at [verus.wattpool.net](https://verus.wattpool.net) - also seeing some nice time savings when using unix domain sockets instead of tcp host:port

Before:
```
2019-07-07 08:41:10 [Pool]      [verus] (Thread 1) Share processing setup with redis (127.0.0.1:6379)
2019-07-07 08:42:09 [Payments]  [verus] Finished interval - time spent: 18ms total, 8ms redis, 9ms daemon RPC
2019-07-07 08:45:09 [Payments]  [verus] Finished interval - time spent: 19ms total, 7ms redis, 4ms daemon RPC

```

After:
```
2019-07-07 18:30:02 [Pool]      [verus] (Thread 1) Share processing setup with redis (/var/run/redis/redis.sock)
2019-07-07 18:32:02 [Payments]  [verus] Finished interval - time spent: 12ms total, 2ms redis, 4ms daemon RPC
2019-07-07 18:35:02 [Payments]  [verus] Finished interval - time spent: 9ms total, 1ms redis, 3ms daemon RPC

**Review by egyptianbman — APPROVED** [review]
Thank you for your contribution!

**Comment by leto** [comment]
Nice work :+1:

**Pull request merged**
