### PR TITLE
Refactored redis version check

### PR DESCRIPTION
**Pull request by Punkoivan**
Was looking through the code and noticed this awful things with split and other things.

As long as we have "server_info.redis_version" object we should use it directly.

Minimal requires version of redis is 2.6 and now we have 4 as a stable and I have doubt do we need this check at all.

Thanks,
Ivan/Nibirupool

### CODE REVIEW

**Review by egyptianbman — CHANGES_REQUESTED** [review]
@Punkoivan can you rebase your master branch? It looks like you have the same commits with different hashes which is causing this PR to show more commits than it should.

**Comment by egyptianbman** [comment]
I'm going to go ahead and close this PR as it seems to just be collecting changes from a fork. @Punkoivan let me know if you need help with setting up a PR for each change; thanks.

**Comment by Punkoivan** [comment]
Okay, sorry, have no time last weeks, I'll clean out my PR and provide only needful changes (the latest one is for redis, I think we can save ms on start)

Thank you!

**Comment by egyptianbman** [comment]
No need to apologize! Let me know if you need any help setting up new PRs.

**Pull request closed without merging**
