### PR TITLE
Clean up configs

### PR DESCRIPTION
**Pull request by egyptianbman**
This is something that has bugged me for quite some time, the configs
have just been thrown together without any conventions. This commit
renames all the config files to their symbol and moves testnet configs
into a testnet directory. I've also synced over some configs that are
available in some files but not in others.

### CODE REVIEW

**Comment by egyptianbman** [comment]
Hmm, git didn't seem to catch some of the renames. Let me see if I can fix that real quick.

**Review by Gumbees — COMMENTED** [review]
Like the short names instead of full names. Just makes everything faster. Can save a lot of time.

Region ID addition is nice. Didn't spot any typos. 

Needs reviewed by another.

**Review by Gumbees — APPROVED** [review]
Tested with zelcash. block found and payments working. json validator passed for all changes.

**Comment by egyptianbman** [comment]
I have some more changes coming but I'm setting up my test environment to make sure the changes don't break anything.

**Comment by egyptianbman** [comment]
Testing hook

**Review by Gumbees — CHANGES_REQUESTED** [review]
Please add zcash overwinter line.

**Comment by egyptianbman** [comment]
OK, this is now ready to review.

**Review by Gumbees — APPROVED** [review]
All changed files ran through json validator. All are valid.

Standards for pool_configs and coins will follow this model. rpcsuser and rpcpassword will be used. Database for mysql mpos will use coin symbol. testnet coin.jsons will be in coins/testnet/coinsymbol.json instead of coins/coinname_testnet.json.

I'll update my branch additions.

**Comment by egyptianbman** [comment]
Thanks!

**Pull request merged**
